CREATE TABLE [USUARIO] (
  [ID] bigint IDENTITY(1, 1),
  [NOMBRE] nvarchar(512) NOT NULL,
  [EMAIL] nvarchar(512) NOT NULL,
  [PASSWORD] nvarchar(256) NOT NULL,
  [TIPO_USUARIO_ID] int NOT NULL,
  CONSTRAINT [PK_USUARIO] PRIMARY KEY([ID])
)
GO

CREATE TABLE [DEMANDANTE] (
  [USUARIO_ID] bigint,
  [FECHA_NACIMIENTO] date NOT NULL,
  [MOVIL] nvarchar(32) NOT NULL,
  [NIVEL_EDUCATIVO_ID] int NOT NULL,
  [PERFIL] nvarchar(1024) NOT NULL,
  CONSTRAINT [PK_DEMANDANTE] PRIMARY KEY([USUARIO_ID])
)
GO

CREATE TABLE [EMPLEADOR] (
  [USUARIO_ID] bigint,
  [LOCALIZACION_ID] int NOT NULL,
  [INDUSTRIA_ID] int NOT NULL,
  [CANTIDAD_EMPLEADOS] int NOT NULL,
  [PERFIL] nvarchar(1024) NOT NULL,
  CONSTRAINT [PK_EMPLEADOR] PRIMARY KEY([USUARIO_ID])
)
GO

CREATE TABLE [VACANTE] (
  [ID] bigint IDENTITY(1, 1),
  [EMPLEADOR_ID] bigint NOT NULL,
  [FECHA_CREACION] datetime NOT NULL,
  [DESCRIPCION] nvarchar(256) NOT NULL,
  [TITULO] nvarchar(256) NOT NULL,
  [REQUISITOS] nvarchar(1024) NOT NULL,
  CONSTRAINT [PK_VACANTE] PRIMARY KEY([ID])
)
GO

CREATE TABLE [TIPO_USUARIO] (
  [ID] int IDENTITY(1, 1),
  [DESCRIPCION] nvarchar(256) UNIQUE NOT NULL,
  CONSTRAINT [PK_TIPO_USUARIO] PRIMARY KEY([ID])
)
GO

CREATE TABLE [NIVEL_EDUCATIVO] (
  [ID] int IDENTITY(1, 1),
  [DESCRIPCION] nvarchar(256) NOT NULL,
  CONSTRAINT [PK_NIVEL_EDUCATIVO] PRIMARY KEY([ID])
)
GO

CREATE TABLE [EXPERIENCIA_LABORAL] (
  [ID] bigint IDENTITY(1, 1),
  [DEMANDANTE_ID] bigint NOT NULL,
  [JEFE_DIRECTO] nvarchar(256) NOT NULL,
  [TELEFONO_CONTACTO] nvarchar(32) NOT NULL,
  [DESCRIPCION_LABOL] nvarchar(1024) NOT NULL,
  [FECHA_INICIO] date NOT NULL,
  [FECHA_FIN] date NOT NULL,
  CONSTRAINT [PK_EXPERIENCIA_LABORAL] PRIMARY KEY([ID])
)
GO

CREATE TABLE [LOCALIZACION] (
  [ID] int IDENTITY(1, 1),
  [DESCRIPCION] nvarchar(256) NOT NULL,
  [DIRECCION] nvarchar(256) NOT NULL,
  [UBICACION] nvarchar(256) NOT NULL,
  CONSTRAINT [PK_LOCALIZACION] PRIMARY KEY([ID])
)
GO

CREATE TABLE [INDUSTRIA] (
  [ID] int IDENTITY(1, 1),
  [DESCRIPCION] nvarchar(256) NOT NULL,
  CONSTRAINT [PK_INDUSTRIA] PRIMARY KEY([ID])
)
GO

CREATE TABLE [EMPAREJAMIENTO] (
  [VACANTE_ID] bigint,
  [DEMANDANTE_ID] bigint,
  CONSTRAINT [PK_EMPAREJAMIENTO] PRIMARY KEY ([VACANTE_ID], [DEMANDANTE_ID])
)
GO

CREATE UNIQUE INDEX [UC_EMPLEADOR_ID_FECHA_CREACION] ON [VACANTE] ("EMPLEADOR_ID", "FECHA_CREACION")
GO

CREATE UNIQUE INDEX [UC_USUARIO_EMAIL] ON [USUARIO] ([EMAIL])
GO

ALTER TABLE [USUARIO] ADD CONSTRAINT [FK_USUARIO_TIPO_USUARIO_ID] FOREIGN KEY ([TIPO_USUARIO_ID]) REFERENCES [TIPO_USUARIO] ([ID])
GO

ALTER TABLE [DEMANDANTE] ADD CONSTRAINT [FK_DEMANDANTE_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [USUARIO] ([ID])
GO

ALTER TABLE [DEMANDANTE] ADD CONSTRAINT [FK_DEMANDANTE_NIVEL_EDUCATIVO_ID] FOREIGN KEY ([NIVEL_EDUCATIVO_ID]) REFERENCES [NIVEL_EDUCATIVO] ([ID])
GO

ALTER TABLE [EMPLEADOR] ADD CONSTRAINT [FK_EMPLEADOR_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [USUARIO] ([ID])
GO

ALTER TABLE [EMPLEADOR] ADD CONSTRAINT [FK_EMPLEADOR_LOCALIZACION_ID] FOREIGN KEY ([LOCALIZACION_ID]) REFERENCES [LOCALIZACION] ([ID])
GO

ALTER TABLE [EMPLEADOR] ADD CONSTRAINT [FK_EMPLEADOR_INDUSTRIA_ID] FOREIGN KEY ([INDUSTRIA_ID]) REFERENCES [INDUSTRIA] ([ID])
GO

ALTER TABLE [VACANTE] ADD CONSTRAINT [FK_VACANTE_EMPLEADOR_ID] FOREIGN KEY ([EMPLEADOR_ID]) REFERENCES [EMPLEADOR] ([USUARIO_ID])
GO

ALTER TABLE [EXPERIENCIA_LABORAL] ADD CONSTRAINT [FK_EXPERIENCIA_LABORAL_DEMANDANTE_ID] FOREIGN KEY ([DEMANDANTE_ID]) REFERENCES [DEMANDANTE] ([USUARIO_ID])
GO

ALTER TABLE [EMPAREJAMIENTO] ADD CONSTRAINT [FK_EMPAREJAMIENTO_VACANTE_ID] FOREIGN KEY ([VACANTE_ID]) REFERENCES [VACANTE] ([ID])
GO

ALTER TABLE [EMPAREJAMIENTO] ADD CONSTRAINT [FK_EMPAREJAMIENTO_DEMANDANTE_ID] FOREIGN KEY ([DEMANDANTE_ID]) REFERENCES [DEMANDANTE] ([USUARIO_ID])
GO